### ISSUE TITLE
Add /fakeblock command

### ISSUE THREAD

**Issue by HeroCC** [HeroiCraft/Core#5]
This command makes blocks appear like another block but doesn't actually exist. Aim to use this with the Bukkit sendBlockChange() function.

Aimed Features:
- [ ] Server Restart Persistent (via custom config file [fakes.yml?])
- [x] Permissionsable (Only players with permission would see the fake blocks, others would see it as normal)
- [ ] More?

PS to @ThunderGemios10, try to follow my code style, use a separate branch than master, and let me know if you need help. Thanks!

**Comment by ThunderGemios10** [comment]
@HeroCC All right! I'll start working on it.

EDIT: I just checked the API Docs. seems sendBlockChange() is deprecated... I will try to find an alternative.. If not i'll use it anyway.

EDIT 2: I'm done on my end. I don't know how to use or interact with the config api.
